version: '3'

services:
  ufsmgo:
    image: mrtrevisan/ufsmgo:latest
    container_name: ufsmgo
    restart: always
    stdin_open: true
    tty: true 
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true