version: '3'

services:
  ufsmgo-sync:
    #image: mrtrevisan/ufsmgo-sync:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufsmgo-sync
    restart: always
    env_file: .env
    stdin_open: true
    tty: true        

    networks:
      - traefik-proxy
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true